<?php $_appName = 'Jungle Pizza'; ?>
<!DOCTYPE html><html lang="es"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#13212b">
<title>Jungle Pizza &mdash; Recuperar contrase&ntilde;a</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Chewy&family=Nunito:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="<?= BASE_URL ?>public/css/jungle-auth.css"></head><body>
<main class="auth-page"><div class="auth-layout"><section class="auth-card" aria-labelledby="forgot-title">
<aside class="auth-story" aria-label="Jungle Pizza en Playa La Ropa"><picture><source media="(max-width:760px)" srcset="<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-760.webp"><img class="auth-photo" src="<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-1600.webp" srcset="<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-760.webp 760w,<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-960.webp 960w,<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-1600.webp 1600w" sizes="(max-width:760px) 100vw,52vw" width="1600" height="878" alt="Pizza de Jungle Pizza junto al horno" fetchpriority="high" decoding="async"></picture><div class="auth-scrim" aria-hidden="true"></div>
<a class="auth-brand" href="<?= BASE_URL ?>" aria-label="Ir al inicio de Jungle Pizza"><img class="auth-logo" src="<?= BASE_URL ?>base/redesign-assets/jungle-pizza-logo-420.webp" width="420" height="338" alt="Jungle Pizza"></a>
<div class="auth-story-content"><span class="auth-location"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21s7-4.35 7-11A7 7 0 105 10c0 6.65 7 11 7 11z"/><circle cx="12" cy="10" r="2.25"/></svg>Playa La Ropa &middot; Zihuatanejo</span><h2 class="auth-story-title">Recupera el acceso a tu restaurante.</h2><p class="auth-story-copy">Vuelve a gestionar reservaciones, mesas, comandas y ventas de Jungle Pizza desde un solo lugar.</p></div></aside>
<section class="auth-panel"><div class="auth-form"><span class="auth-kicker">Administraci&oacute;n de Jungle Pizza</span><h1 class="auth-title" id="forgot-title">&iquest;Olvidaste tu contrase&ntilde;a?</h1><p class="auth-intro">Ingresa el correo de tu cuenta y te enviaremos un enlace seguro para restablecerla.</p>
<?php if (!empty($flash)): $isError=($flash['type']??'')==='error'; ?><div class="auth-flash <?= $isError?'is-error':'is-success' ?>" role="<?= $isError?'alert':'status' ?>" aria-live="polite"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path stroke-linecap="round" d="M12 7.5v5M12 16.5h.01"/></svg><span><?= htmlspecialchars((string)$flash['message']) ?></span></div><?php endif; ?>
<form method="POST" action="<?= BASE_URL ?>auth/sendReset"><div class="auth-field"><label class="auth-label" for="forgot-email">Correo electr&oacute;nico</label><div class="auth-control"><span class="auth-icon" aria-hidden="true"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.9"><path stroke-linecap="round" d="M3.5 7.5l7.2 5a2.25 2.25 0 002.6 0l7.2-5M5.5 19h13a2 2 0 002-2V7a2 2 0 00-2-2h-13a2 2 0 00-2 2v10a2 2 0 002 2z"/></svg></span><input class="auth-input" type="email" id="forgot-email" name="email" placeholder="admin@junglezihua.com" required autocomplete="email" autocapitalize="none" spellcheck="false" autofocus></div></div><button class="auth-submit" type="submit">Enviar enlace de recuperaci&oacute;n</button></form>
<a class="auth-back" href="<?= BASE_URL ?>auth/login"><span aria-hidden="true">&larr;</span> Volver al inicio de sesi&oacute;n</a></div></section>
</section></div></main></body></html>
