<?php $_token=htmlspecialchars((string)($token??''),ENT_QUOTES,'UTF-8'); ?>
<!DOCTYPE html><html lang="es"><head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="theme-color" content="#13212b">
<title>Jungle Pizza &mdash; Nueva contrase&ntilde;a</title>
<link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css2?family=Chewy&family=Nunito:wght@400;500;600;700;800;900&display=swap" rel="stylesheet">
<link rel="stylesheet" href="<?= BASE_URL ?>public/css/jungle-auth.css"></head><body>
<main class="auth-page"><div class="auth-layout"><section class="auth-card" aria-labelledby="reset-title">
<aside class="auth-story" aria-label="Jungle Pizza en Playa La Ropa"><picture><source media="(max-width:760px)" srcset="<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-760.webp"><img class="auth-photo" src="<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-1600.webp" srcset="<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-760.webp 760w,<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-960.webp 960w,<?= BASE_URL ?>base/redesign-assets/hero-jungle-pizza-1600.webp 1600w" sizes="(max-width:760px) 100vw,52vw" width="1600" height="878" alt="Pizza de Jungle Pizza junto al horno" fetchpriority="high" decoding="async"></picture><div class="auth-scrim" aria-hidden="true"></div>
<a class="auth-brand" href="<?= BASE_URL ?>" aria-label="Ir al inicio de Jungle Pizza"><img class="auth-logo" src="<?= BASE_URL ?>base/redesign-assets/jungle-pizza-logo-420.webp" width="420" height="338" alt="Jungle Pizza"></a>
<div class="auth-story-content"><span class="auth-location"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" d="M12 21s7-4.35 7-11A7 7 0 105 10c0 6.65 7 11 7 11z"/><circle cx="12" cy="10" r="2.25"/></svg>Playa La Ropa &middot; Zihuatanejo</span><h2 class="auth-story-title">Tu operaci&oacute;n, segura y bajo control.</h2><p class="auth-story-copy">Crea una nueva contrase&ntilde;a para volver al panel administrativo de Jungle Pizza.</p></div></aside>
<section class="auth-panel"><div class="auth-form"><span class="auth-kicker">Acceso seguro</span><h1 class="auth-title" id="reset-title">Crea tu nueva contrase&ntilde;a</h1><p class="auth-intro">Utiliza al menos 8 caracteres y evita contrase&ntilde;as que ya uses en otros servicios.</p>
<?php if (!empty($flash)): $isError=($flash['type']??'')==='error'; ?><div class="auth-flash <?= $isError?'is-error':'is-success' ?>" role="<?= $isError?'alert':'status' ?>" aria-live="polite"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2" aria-hidden="true"><circle cx="12" cy="12" r="9"/><path stroke-linecap="round" d="M12 7.5v5M12 16.5h.01"/></svg><span><?= htmlspecialchars((string)$flash['message']) ?></span></div><?php endif; ?>
<form method="POST" action="<?= BASE_URL ?>auth/doReset"><input type="hidden" name="token" value="<?= $_token ?>">
<div class="auth-field"><label class="auth-label" for="pw1">Nueva contrase&ntilde;a</label><div class="auth-control"><span class="auth-icon" aria-hidden="true"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.9"><rect x="4.5" y="10.5" width="15" height="10" rx="2"/><path stroke-linecap="round" d="M8 10.5V7.75a4 4 0 018 0v2.75"/></svg></span><input class="auth-input" type="password" name="password" id="pw1" placeholder="M&iacute;nimo 8 caracteres" minlength="8" required autocomplete="new-password"><button class="auth-toggle" type="button" data-toggle="pw1" aria-label="Mostrar nueva contrase&ntilde;a" aria-pressed="false"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.9" aria-hidden="true"><path stroke-linecap="round" d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6z"/><circle cx="12" cy="12" r="2.75"/></svg></button></div></div>
<div class="auth-field"><label class="auth-label" for="pw2">Confirmar contrase&ntilde;a</label><div class="auth-control"><span class="auth-icon" aria-hidden="true"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.9"><rect x="4.5" y="10.5" width="15" height="10" rx="2"/><path stroke-linecap="round" d="M8 10.5V7.75a4 4 0 018 0v2.75"/></svg></span><input class="auth-input" type="password" name="password_confirm" id="pw2" placeholder="Repite tu contrase&ntilde;a" minlength="8" required autocomplete="new-password"><button class="auth-toggle" type="button" data-toggle="pw2" aria-label="Mostrar confirmaci&oacute;n" aria-pressed="false"><svg fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="1.9" aria-hidden="true"><path stroke-linecap="round" d="M2.5 12s3.5-6 9.5-6 9.5 6 9.5 6-3.5 6-9.5 6-9.5-6-9.5-6z"/><circle cx="12" cy="12" r="2.75"/></svg></button></div></div><p class="auth-hint">Ambas contrase&ntilde;as deben coincidir.</p><button class="auth-submit" type="submit">Guardar nueva contrase&ntilde;a</button></form>
<a class="auth-back" href="<?= BASE_URL ?>auth/login"><span aria-hidden="true">&larr;</span> Volver al inicio de sesi&oacute;n</a></div></section>
</section></div></main><script>document.querySelectorAll('[data-toggle]').forEach(function(b){b.addEventListener('click',function(){var i=document.getElementById(b.dataset.toggle),show=i.type==='password';i.type=show?'text':'password';b.setAttribute('aria-pressed',show?'true':'false');b.setAttribute('aria-label',(show?'Ocultar':'Mostrar')+' contraseña');i.focus({preventScroll:true})})});</script></body></html>
